version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: your_database_name # Optional
      MYSQL_USER: your_username # Optional
      MYSQL_PASSWORD: your_password # Optional
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
